steps:
- name: node:14.17.1
  entrypoint: yarn
  args: ["install"]
- name: node:14.17.1
  entrypoint: yarn
  args: ["build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
